version: '3.8'

services:
  app:
    build: .
    ports:
      - "7777:7777"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/finance_flow
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345679
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=finance_flow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345679
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: